
import React, { useState, useEffect } from 'react';
import { X, Loader2, Sparkles, AlertCircle, CheckCircle2 } from 'lucide-react';
import { Player } from '../types';
import { generateScoutingReport } from '../services/geminiService';

interface ScoutingModalProps {
  player: Player | null;
  onClose: () => void;
}

const ScoutingModal: React.FC<ScoutingModalProps> = ({ player, onClose }) => {
  const [report, setReport] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);

  useEffect(() => {
    if (player) {
      const fetchReport = async () => {
        setLoading(true);
        const result = await generateScoutingReport(player);
        setReport(result);
        setLoading(false);
      };
      fetchReport();
    }
  }, [player]);

  if (!player) return null;

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg overflow-hidden transform transition-all">
        <div className="bg-black text-white px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <Sparkles size={20} className="text-blue-400" />
            <h3 className="font-semibold">AI Scouting Report</h3>
          </div>
          <button onClick={onClose} className="hover:text-gray-300 transition-colors">
            <X size={20} />
          </button>
        </div>
        
        <div className="p-6">
          <div className="flex justify-between items-start mb-4">
            <div>
              <h4 className="text-2xl font-bold text-gray-900">{player.name}</h4>
              <div className="flex gap-4 text-sm text-gray-500 mt-1">
                <span>Pos: {player.position}</span>
                <span>Clutch: {player.clutchFactor}</span>
                {player.graduationYear && <span>Grad: {player.graduationYear}</span>}
              </div>
            </div>
            
            <div className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider flex items-center gap-1.5 ${player.needsRetest ? 'bg-red-50 text-red-600 border border-red-100' : 'bg-emerald-50 text-emerald-600 border border-emerald-100'}`}>
              {player.needsRetest ? (
                <>
                  <AlertCircle size={12} />
                  Retest Needed
                </>
              ) : (
                <>
                  <CheckCircle2 size={12} />
                  Valid Data
                </>
              )}
            </div>
          </div>

          <div className="bg-gray-50 rounded-lg p-5 border border-gray-100 min-h-[160px] flex flex-col justify-center">
            {loading ? (
              <div className="flex flex-col items-center gap-3 text-gray-400">
                <Loader2 className="animate-spin" size={32} />
                <p className="text-sm font-medium">Analyzing performance metrics...</p>
              </div>
            ) : (
              <p className="text-gray-700 leading-relaxed italic">
                "{report}"
              </p>
            )}
          </div>

          <div className="mt-6 flex justify-between items-center">
            <p className="text-[10px] text-gray-400 uppercase tracking-widest">
              Generated by Gemini 3 Flash
            </p>
            <button
              onClick={onClose}
              className="px-6 py-2 bg-black text-white rounded-lg hover:bg-gray-800 transition-colors text-sm font-semibold"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ScoutingModal;
